### ISSUE TITLE
Restricted to local databases

### ISSUE THREAD

**Issue by levidurfee** [ResulPolat/Node-MySQL-Import#1]
Is there a reason this only works on local databases? I have a database on the same local network, and would like to use this. :)

https://github.com/ResulPolat/Node-MySQL-Import/blob/master/lib/index.js#L17

**Comment by ressieboy** [comment]
Short answer: It was meant to be used on a local database.

Long answer: It was meant to be used on a local database in order to enable desktop developers to import large precompiled datasets using native binaries for speed and performance. 

Doing a remote import using a MySQL connection and 1 million queries is not that efficient and would take a lot of time. Now if you have a small dataset, there are a couple of other options available.
